# conda env for nf-test
# https://github.com/askimed/nf-test

# name: nf-test
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - nextflow>=23
  - nf-test>=0.8
  - python>=3.12
  - prettier
  # - pip
  # pip install --upgrade --force-reinstall git+https://github.com/nf-core/tools.git@dev


# nf-test quick guide;
# $ nf-test test --tag vcf2maf --profile docker --update-snapshot
# $ nf-core modules lint vcf2maf
# $ prettier --check .
