# $ conda env create -f environment.yml -n nextflow
# $ conda activate nextflow
name: nextflow
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - nextflow
  - graphviz
  - pytest-workflow # make sure to get the version from conda-forge !!
  # - nf-core # this causes the conda install to take a looooooong time ??
  # - prettier